[package]
name = "branches"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "=1.0.55"
git2 = "=0.14.1"
json5 = "=0.4.1"
serde = { version = "=1.0.136", features = ["derive"] }
term = "=0.7.0"
